spring.application.name=mycellium
spring.datasource.url=jdbc:mysql://localhost:3306/mycellium
spring.datasource.username=root
spring.datasource.password=Euphoric18@Something11@2004?

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true