ALTER TABLE events
    ADD COLUMN university VARCHAR(255) NULL,
    ADD COLUMN event_type VARCHAR(255) NULL,
    ADD COLUMN start_date DATETIME(6) NULL,
    ADD COLUMN end_date DATETIME(6) NULL,
    ADD COLUMN registration_deadline DATETIME(6) NULL,
    ADD COLUMN status VARCHAR(50) NULL DEFAULT 'PUBLISHED',
    ADD COLUMN about TEXT NULL,
    ADD COLUMN created_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
    ADD COLUMN updated_at DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);
